import { ArchiveIcon, NewspaperIcon, UserGroupIcon } from '@heroicons/react/solid'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Demo Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className="bg-hero h-screen w-full px-4 lg:px-32">
          <div className="h-full flex flex-col justify-center space-y-4">
            <h1 className="text-white text-6xl">Lets be the change we want to create</h1>
            <div className="text-3xl">
              <p className="text-gray-200">Be part of this great change</p>
              <p className="text-gray-500">Derick Chilundika</p>
            </div>
            <div className="divider p-1 bg-white w-16"></div>
            <div className="grid grid-cols-3 bg-white rounded-full  lg:w-1/3 z-40 h-auto p-2 relative top-20">
                <div className="flex flex-col justify-center items-center">
                  <NewspaperIcon className="h-8 w-8 text-blue-800"/>
                  <p className="text-xs text-gray-600">Apply for funding</p>
                </div>
                <div className="flex flex-col justify-center items-center">
                  <ArchiveIcon className="h-8 w-8 text-blue-800"/>
                  <p className="text-xs text-gray-600">Ward Projects</p>
                </div>
                <div className="flex flex-col justify-center items-center">
                  <UserGroupIcon className="h-8 w-8 text-blue-800"/>
                  <p className="text-xs text-gray-600">Lets get talking</p>
                </div>
                <div className=""></div>
            </div>
          </div>
         
      </section>
      <main className="px-4 py-8 lg:px-32">
          <h1 className="text-4xl text-blue-800">Our Ward</h1>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
            <div className="flex flex-col justify-center p-2 lg:p-4 bg-gray-100 rounded-2xl space-y-3">
                <div className="relative w-fill h-60 rounded-2xl">
                  <Image src="/ward.jpg" layout="fill" objectFit="cover" className="rounded-2xl"/>
                </div>
                <h1 className="text-2xl pt-2">Nchanga Ward at a glance</h1>
                <p className="text-gray-500 jus text-justify">Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et d lorem ipsum dolor. Lorem ipsum dolor sit.
                Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et d lorem ipsum dolor. Lorem ipsum dolor sit
                </p>
                <button type="button" className="bg-blue-800 p-4 text-white rounded-full">View More</button>
            </div>
            <div className="flex flex-col justify-center p-2  bg-gray-100 rounded-2xl space-y-3">
                <div className="relative w-fill h-60 rounded-2xl">
                  <Image src="/people.jpg" layout="fill" objectFit="cover" className="rounded-2xl"/>
                </div>
                <h1 className="text-2xl pt-2">The People</h1>
                <p className="text-gray-500 jus text-justify">Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et d lorem ipsum dolor. Lorem ipsum dolor sit.
                Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et d lorem ipsum dolor. Lorem ipsum dolor sit
                </p>
                <button type="button" className="bg-blue-800 p-4 text-white rounded-full">View More</button>
            </div>
            <div className="flex flex-col justify-center p-2 lg:p-4 bg-gray-100 rounded-2xl space-y-3">
                <div className="relative w-fill h-60 rounded-2xl">
                  <Image src="/sport.jpg" layout="fill" objectFit="cover" className="rounded-2xl"/>
                </div>
                <h1 className="text-2xl pt-2">Recreational Facilities</h1>
                <p className="text-gray-500 jus text-justify">Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et d lorem ipsum dolor. Lorem ipsum dolor sit.
                Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et d lorem ipsum dolor. Lorem ipsum dolor sit
                </p>
                <button type="button" className="bg-blue-800 p-4 text-white rounded-full">View More</button>
            </div>
            <div className="flex flex-col justify-center p-2 lg:p-4 bg-gray-100 rounded-2xl space-y-3">
                <div className="relative w-fill h-60 rounded-2xl">
                  <Image src="/clinic.jpg" layout="fill" objectFit="cover" className="rounded-2xl"/>
                </div>
                <h1 className="text-2xl pt-2">Social Services</h1>
                <p className="text-gray-500 jus text-justify">Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et d lorem ipsum dolor. Lorem ipsum dolor sit.
                Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et d lorem ipsum dolor. Lorem ipsum dolor sit
                </p>
                <button type="button" className="bg-blue-800 p-4 text-white rounded-full">View More</button>
            </div>
          </div>

      </main>
      <section className="px-2 py-8 bg-blue-800 space-y-3 lg:px-32">
        <h1 className="text-4xl text-white">Current Projects</h1>
       <div className="grid grid-cols-1 gap-3 lg:grid-cols-3">
        <div className="flex flex-col justify-center p-2 lg:p-4 bg-white rounded-2xl space-y-3">
              <div className="relative w-fill h-60 rounded-2xl">
                <Image src="/school.jpg" layout="fill" objectFit="cover" className="rounded-2xl"/>
              </div>
              <h1 className="text-2xl pt-2">Community School</h1>
              <p className="text-gray-500 jus text-justify">Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et d lorem ipsum dolor. Lorem ipsum dolor sit.
              Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et d lorem ipsum dolor. Lorem ipsum dolor sit
              </p>
              <button type="button" className="bg-blue-800 p-4 text-white rounded-full">View More</button>
          </div>
          <div className="flex flex-col justify-center p-2 lg:p-4 bg-white rounded-2xl space-y-3">
              <div className="relative w-fill h-60 rounded-2xl">
                <Image src="/water.jpg" layout="fill" objectFit="cover" className="rounded-2xl"/>
              </div>
              <h1 className="text-2xl pt-2">Water Project</h1>
              <p className="text-gray-500 jus text-justify">Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et d lorem ipsum dolor. Lorem ipsum dolor sit.
              Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et d lorem ipsum dolor. Lorem ipsum dolor sit
              </p>
              <button type="button" className="bg-blue-800 p-4 text-white rounded-full">View More</button>
          </div>
          <div className="flex flex-col justify-center p-2 lg:p-4 bg-white rounded-2xl space-y-3">
              <div className="relative w-fill h-60 rounded-2xl">
                <Image src="/irrigation.jpg" layout="fill" objectFit="cover" className="rounded-2xl"/>
              </div>
              <h1 className="text-2xl pt-2">Water Irrigation</h1>
              <p className="text-gray-500 jus text-justify">Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et d lorem ipsum dolor. Lorem ipsum dolor sit.
              Lorem ipsum dolor sit amet, consectetur, sed do eiusmod tempor incididunt ut labore et d lorem ipsum dolor. Lorem ipsum dolor sit
              </p>
              <button type="button" className="bg-blue-800 p-4 text-white rounded-full">View More</button>
          </div>
       </div>
      </section>
      <section className="flex flex-col items-center space-y-3 justify-center py-10 bg-transparent px-2 lg:px-32">
        <h1 className="text-4xl text-blue-800">Join our mailing list</h1>
        <div className="flex flex-col space-y-3 w-1/3">
          <input type="text" className="w-full bg-transparent border border-blue-800 p-4 rounded-full" placeholder="Email Address"/>
          <button type="button" className="bg-blue-800 p-4 text-white rounded-full">View More</button>
        </div>
      </section>
      <section className="flex flex-col items-center space-y-3 justify-center py-5 bg-transparent px-2 bg-gray-800">
        <div className="flex flex-col space-y-3 w-full">
          <p className="text-gray-300 text-center">Copyright &copy; 2021 | Nchanga Ward</p>
        </div>
      </section>
      <Footer />
     
    </div>
  )
}
